cfg_path: ???
tokenizer_cfg_path: configs/tokenizer/seed_llama_tokenizer_hf.yaml
transform_cfg_path: configs/transform/clip_transform.yaml
model_cfg_path: configs/llm/seed_llama_8b.yaml 
result_file_path: ./logs/nsvq_with_loss_balance
checkpoint_path:
  model_path: pretrained/seed_tokenizer/seed_quantizer.pt
  diffusion_model_path: stabilityai/stable-diffusion-2-1-unclip

resume: False
load_weight: False
weight_path: None
# weight_path: /home/ubuntu/Projects/SEED_Tokenizer/logs/current_training/nsvq_with_codebook_replacement/checkpoints/epoch=0-step=2000.ckpt
eval: False

dist:
  n_gpus: 8
  n_nodes: 1

dataset:
  train_config:
    dataset_configs: ['configs/data_aica/cc15m.yaml', 'configs/data_aica/laion-coco-total.yaml', 'configs/data_aica/mscoco.yaml', 'configs/data_aica/unsplash.yaml']
    weights: [10, 50, 1, 5]
    shardshuffle: 100
    resampled: True
    world_size: 1
    one_epoch_data_size: 1000000
  val_config:
    use_coco_val: True
    karpathy_file_path: /data/magvlt2/data/coco/annotations/karpathy/dataset_coco_train.json
    root_dir: /data/magvlt2/data/coco/images/val2014
    start_index: 0
    end_index: 512
  num_workers: 16
  shuffle: True
  text_max_length: 128

stage1:
  init: 'SEED'

stage2:
  bypass_codebook: False
  load_diffusion: True
  vq:
    type: 'nsvq' # ['vq2', 'ema_vq', nsvq']
    legacy: False
    replace_codes: True
    replacement_num_batches: 1000
    discarding_threshold: 0.1
  loss_weight:
    loss_codebook: 1
    loss_recon: 4
    loss_generation_embedding: 1 
  recon_s: True

experiment:
  seed: 0
  stage: 2
  local_batch_size: 2048
  val_batch_size: 16
  test_split: train
  max_epochs: 500
  deterministic: False
  grad_accumulation: 1
  check_val_every_n_epoch: 1
  # val_check_interval: 200
  enable_checkpointing: True
  log_every_n_steps: 1
  num_sanity_val_steps: 1
  num_warmup_steps: 200
  grad_clip_val: 5

optimizer:
  vit_precision: 'fp16'
  diffusion_precision: 'fp16'
  precision: '32'
  max_lr: 1e-3

hyperparameters:
  beta_1: 0.9
  beta_2: 0.999
  weight_decar: 5e-4