cfg_path: ???
tokenizer_cfg_path: configs/tokenizer/seed_llama_tokenizer_hf.yaml
transform_cfg_path: configs/transform/clip_transform.yaml
model_cfg_path: configs/llm/seed_llama_8b.yaml 
result_file_path: ./logs/vq_with_official_config_fixed_fp32
checkpoint_path:
  model_path: pretrained/seed_tokenizer/seed_quantizer.pt
  diffusion_model_path: stabilityai/stable-diffusion-2-1-unclip

resume: False
load_weight: False
# weight_path: /home/zheedong/Projects/SEED/logs/vq_with_official_config_fixed_fp32/lightning_logs/version_1/checkpoints/epoch=45-step=5658.ckpt 
# weight_path: /home/zheedong/Projects/SEED/logs/vq_with_official_config_fixed_fp32/lightning_logs/version_2/checkpoints/epoch=48-step=6027.ckpt 
weight_path: None
eval: False

dist:
  n_gpus: 8
  n_nodes: 1

dataset:
  train_config:
    dataset_configs: ['configs/data/cc15m.yaml', 'configs/data/laion-coco-total.yaml', 'configs/data/mscoco.yaml']
    weights: [10, 660, 1]
    shardshuffle: 100
    resampled: True
    world_size: 1
    one_epoch_data_size: 1000000
  val_config:
    use_coco_val: True
    karpathy_file_path: /ssd0/data/coco/annotations/karpathy/dataset_coco_test.json
    root_dir: /ssd0/data/coco/images/val2014
    start_index: 0
    end_index: 512
  num_workers: 16
  shuffle: True
  text_max_length: 128

stage1:
  init: 'SEED'

stage2:
  bypass_codebook: False
  load_diffusion: True
  vq:
    type: 'vq2' # ['vq2', 'ema_vq', nsvq']
    replace_codes: True
    replacement_num_batches: 1000
    discarding_threshold: 0.01
  loss_weight:
    loss_codebook: 5
    loss_recon: 2
    loss_generation_embedding: 0.5

experiment:
  seed: 0
  stage: 2
  local_batch_size: 1024
  val_batch_size: 16
  test_split: train
  max_epochs: 500
  deterministic: False
  grad_accumulation: 1
  check_val_every_n_epoch: 2
  # val_check_interval : 200
  enable_checkpointing: True
  log_every_n_steps: 1
  num_sanity_val_steps: 1
  num_warmup_steps: 500
  grad_clip_val: 5

optimizer:
  vit_precision: 'fp16'
  diffusion_precision: 'fp16'
  precision: '32'
  max_lr: 1e-3

hyperparameters:
  beta_1: 0.9
  beta_2: 0.999
  weight_decay: 5e-2
