cfg_path: ???
tokenizer_cfg_path: configs/tokenizer/seed_llama_tokenizer_hf.yaml
# transform_cfg_path: configs/transform/clip_transform.yaml
transform_cfg_path: configs/transform/slot_transform.yaml
model_cfg_path: configs/llm/seed_llama_8b.yaml 
result_file_path: ./logs/slot_quantization
# result_file_path: ./logs/seed_slot_layer1
checkpoint_path:
  model_path: pretrained/seed_tokenizer/seed_quantizer.pt
  diffusion_model_path: stabilityai/stable-diffusion-2-1-unclip
slot_cfg_path: configs/slot_attn/config_12heads_dino.json

test: False
resume: False
load_weight: True
weight_path: pretrained/seed_slot_layer1_dino_12head_dataaug_learnablequery_200epoch_crossattn_unfreeze/checkpoints/epoch=88-step=122926.ckpt
# weight_path: pretrained/nsvq_train_blocks_image_freeze_unet_linear_8_blocks_768_embed_dim_16384_codebook_dim_6gpus/checkpoints/epoch=63-step=20863.ckpt
# weight_path: logs/slot_quantization_related/residual_vq_train_blocks_image_unfreeze_unet_linear_4_blocks_4_blocks_image_64_embed_dim_16384_codebook_dim_6gpus_data_ratio_multi_head_8_shared_codebook/checkpoints/epoch=71-step=46943.ckpt
# weight_path: logs/slot_quantization_related/residual_vq_train_blocks_image_unfreeze_unet_linear_4_blocks_4_blocks_image_32_embed_dim_16384_codebook_dim_4gpus_data_ratio_multi_head_8_shared_codebook_resume_6gpus/checkpoints/epoch=56-step=43013.ckpt
eval: False

dist:
  n_gpus: 4
  n_nodes: 1

dataset:
  train_config:
    # dataset_configs: ['configs/data/cc15m.yaml', 'configs/data/laion-coco.yaml', 'configs/data/mscoco.yaml', 'configs/data/unsplash.yaml']
    # weights: [15, 24, 1, 4]
    dataset_configs: ['configs/data/cc15m.yaml', 'configs/data/laion-coco.yaml', 'configs/data/mscoco.yaml']
    weights: [1, 6, 4]
    # dataset_configs: ['configs/data/cc15m.yaml', 'configs/data/laion-coco.yaml']
    # weights: [15, 24]
    shardshuffle: 100
    resampled: True
    world_size: 1
    one_epoch_data_size: 1000000
  val_config:
    use_coco_val: True
    karpathy_file_path: coco/annotations/karpathy/dataset_coco_test.json
    root_dir: coco/images/val2014
    start_index: 0
    end_index: 1024
    # end_index:
  num_workers: 16
  shuffle: True
  text_max_length: 128

stage1:
  loss_weight:
    loss_codebook: 5
    loss_recon: 2
    loss_diffusion: 0.5
  unfreeze_unet: True
  unfreeze_linear: False
  blocks_layers: 4
  blocks_image_layers: 4 
  use_blocks_image: False
  unclip: False
  vq:
    vq_type: 'residual_vq'
    num_quantizers: 8
    shared_codebook: True
    # sample_codebook_temp: 0.1
    # kmeans_iters: 10
    # use_cosine_sim: True
    # threshold_ema_dead_code: 10
    codebook_embed_dim: 32
    # n_embed: 8192
    # codebook_embed_dim: 768
    n_embed: 16384

    # replace_codes: True
    # replacement_num_batches: 1000
    # discarding_threshold: 0.1
  bypass_codebook: False

experiment:
  seed: 0
  stage: 2
  local_batch_size: 128
  val_batch_size: 128
  test_split: train
  max_epochs: 100
  deterministic: False
  grad_accumulation: 2
  val_check_interval: 0.5
  # check_val_every_n_epoch: 1 
  enable_checkpointing: True
  log_every_n_steps: 1
  num_sanity_val_steps: 1
  # num_warmup_steps: 200
  num_warmup_steps: 500
  grad_clip_val: 5
  find_unused_parameters: True

optimizer:
  vit_precision: 'fp16'
  diffusion_precision: 'fp16'
  precision: '16'
  max_lr: 1e-4

hyperparameters:
  beta_1: 0.9
  beta_2: 0.999
  weight_decay: 1e-2
  # beta_1: 0.5
  # beta_2: 0.9
  # weight_decay: 0.0