cfg_path: ???
tokenizer_cfg_path: configs/tokenizer/seed_llama_tokenizer_hf.yaml
# transform_cfg_path: configs/transform/clip_transform.yaml
transform_cfg_path: configs/transform/slot_transform.yaml
model_cfg_path: configs/llm/seed_llama_8b.yaml 
result_file_path: ./logs/slot_quantization_debug
# result_file_path: ./logs/seed_slot_layer1
checkpoint_path:
  model_path: pretrained/seed_tokenizer/seed_quantizer.pt
  diffusion_model_path: stabilityai/stable-diffusion-2-1-unclip
slot_cfg_path: /home/zheedong/Projects/latent-slot-diffusion/configs/coco/slot_attn/config_12heads_dino.json

resume: False
load_weight: True
weight_path: /home/zheedong/Projects/SEED/logs/slot_stage1_related/seed_slot_layer1_dino_12head_dataaug_learnablequery_200epoch_crossattn_unfreeze/checkpoints/epoch=88-step=122926.ckpt
# load_weight: False
# weight_path: 
eval: False

dist:
  n_gpus: 1
  n_nodes: 1

dataset:
  train_config:
    dataset_configs: ['configs/data/cc15m.yaml', 'configs/data/laion-coco.yaml', 'configs/data/mscoco.yaml']
    weights: [1, 6, 4]
    shardshuffle: 100
    resampled: True
    world_size: 1
    one_epoch_data_size: 1000000
  val_config:
    use_coco_val: True
    karpathy_file_path: /ssd0/data/coco/annotations/karpathy/dataset_coco_test.json
    root_dir: /ssd0/data/coco/images/val2014
    start_index: 0
    end_index: 256
  num_workers: 16
  shuffle: True
  text_max_length: 128

stage1:
  init: 'BLIP-2'
  use_slot: True
  use_diffusion_loss: True
  use_causal: True
  loss_weight:
    loss_codebook: 10
    loss_recon: 2
    loss_diffusion: 5
  unfreeze_unet: True
  unfreeze_linear: True
  recon_transformer_layers: 4
  use_blocks_image: True

stage2:
  bypass_codebook: False
  load_diffusion: True
  vq:
    type: 'nsvq' # ['vq2', 'ema_vq', nsvq']
    legacy: False
    replace_codes: True
    replacement_num_batches: 1000
    discarding_threshold: 0.1
  loss_weight:
    loss_codebook: 1
    loss_recon: 4
    loss_generation_embedding: 1 
  recon_s: True
  unclip: False

experiment:
  seed: 0
  stage: 1
  local_batch_size: 16
  val_batch_size: 16
  test_split: train
  max_epochs: 200
  deterministic: False
  grad_accumulation: 2
  val_check_interval: 0.5
  # check_val_every_n_epoch: 1 
  enable_checkpointing: False
  log_every_n_steps: 1
  num_sanity_val_steps: 1
  num_warmup_steps: 200
  grad_clip_val: 5

optimizer:
  vit_precision: 'fp16'
  diffusion_precision: 'fp16'
  precision: '16'
  max_lr: 1e-4

hyperparameters:
  beta_1: 0.9
  beta_2: 0.999
  weight_decay: 1e-2