cfg_path: ???
tokenizer_cfg_path: configs/tokenizer/seed_llama_tokenizer_hf.yaml
transform_cfg_path: configs/transform/clip_transform.yaml
model_cfg_path: configs/llm/seed_llama_8b.yaml 
result_file_path: ./logs/long_caption_finetuning
checkpoint_path:
  model_path: pretrained/seed_tokenizer/seed_quantizer.pt
  diffusion_model_path: stabilityai/stable-diffusion-2-1-unclip

resume: False
load_weight: False
# weight_path: /home/zheedong/Projects/SEED/logs/long_caption_debug/stage1_v1/epoch=39-step=11120.ckpt
weight_path: None
eval: False

dist:
  n_gpus: 2
  n_nodes: 1

dataset:
  val_config:
    karpathy_file_path: /ssd0/data/coco/annotations/karpathy/dataset_coco_test.json
    root_dir: /ssd0/data/coco/images/val2014
  num_workers: 8
  shuffle: True
  text_max_length: 512

stage1:
  init: 'SEED'

stage2:
  bypass_codebook: False
  load_diffusion: False

experiment:
  seed: 0
  stage: 1
  local_batch_size: 128
  val_batch_size: 16
  test_split: train
  max_epochs: 40
  deterministic: False
  grad_accumulation: 1
  check_val_every_n_epoch: 1
  enable_checkpointing: True
  log_every_n_steps: 1
  num_sanity_val_steps: 1
  num_warmup_steps: 50

optimizer:
  vit_precision: 'fp16'
  diffusion_precision: 'fp16'
  precision: 'bf16'
  max_lr: 5e-6
  grad_clip_val: 0.5

hyperparameters:
  beta_1: 0.9
  beta_2: 0.999
  weight_decay: 5e-2

