cfg_path: ???
tokenizer_cfg_path: configs/tokenizer/seed_llama_tokenizer_hf.yaml
transform_cfg_path: configs/transform/diffusion_transform.yaml
model_cfg_path: configs/llm/seed_llama_8b.yaml 
result_path: none
result_file_path: ./logs/overfitting_test_debug
checkpoint_path:
  model_path: pretrained/seed_tokenizer/seed_quantizer.pt
  diffusion_model_path: stabilityai/stable-diffusion-2-1-unclip
eval: False
resume: False
finetune: False

dist:
  n_gpus: 2
  n_nodes: 1

dataset:
  type: webdataset
  name: mscoco
  loc: bcloud
  num_workers: 32 
  shuffle: True
  tokenizer:
    type: ClipBPE
    hparams:
      context_length: 64
      bpe_pdrop: 0.1
  transform:
    type: dalle-vqvae
    hparams:
      resolution: 256
  gt_text: True

stage1:
  ema_update: False

stage2:
  image_caption_ratio: 0.5

experiment:
  seed: 0
  local_batch_size: 1
  val_batch_size: 1
  test_split: train
  max_epochs: 50
  grad_accumulation: 1
  overfit_batches: 1
  val_check_interval: 100

optimizer:
  fp16: False
  grad_clip_val: 0.5
