cfg_path: ???
result_path: ???
result_file_path: ???
checkpoint_path: ???
eval: False
resume: False
finetune: False

dist:
  n_gpus: 4
  n_nodes: 1

dataset:
  type: webdataset
  name: cc3m_coco
  loc: bcloud
  num_workers: 4
  shuffle: True
  tokenizer:
    type: ClipBPE
    hparams:
      context_length: 64
      bpe_pdrop: 0.1
  transform:
    type: dalle-vqvae
    hparams:
      resolution: 256
  gt_text: True

stage1:
  ema_update: False

stage2:
  image_caption_ratio: 0.5


experiment:
  seed: 0
  local_batch_size: 1024
  val_batch_size: 256
  test_split: train
  max_epochs: 4

optimizer:
  fp16_grad_comp: True
